# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglikeCpp <- function(X, b, y) {
    .Call('predkmeans_loglikeCpp', PACKAGE = 'predkmeans', X, b, y)
}

gradientMultinomialCpp <- function(X, b, y) {
    .Call('predkmeans_gradientMultinomialCpp', PACKAGE = 'predkmeans', X, b, y)
}

hessianMultinomialCpp <- function(X, b, y, p, k) {
    .Call('predkmeans_hessianMultinomialCpp', PACKAGE = 'predkmeans', X, b, y, p, k)
}

getUproxy <- function(X, b, y) {
    .Call('predkmeans_getUproxy', PACKAGE = 'predkmeans', X, b, y)
}

getExpMahalRcpp <- function(x, center, sigma2) {
    .Call('predkmeans_getExpMahalRcpp', PACKAGE = 'predkmeans', x, center, sigma2)
}

getHRcpp <- function(x, R, gamma, mu, sigma2) {
    .Call('predkmeans_getHRcpp', PACKAGE = 'predkmeans', x, R, gamma, mu, sigma2)
}

